export default {
  SUBMISSION_CREATED: 1,
  SUBMISSION_UPDATED: 2,
  DOCUMENT_APPROVED: 3,
  DOCUMENT_REJECTED: 4,
  FINANCE_APPROVED: 5,
  FINANCE_REJECTED: 6,
  ORDER_STARTED: 7,
  ORDER_FINISHED: 8,
  ORDER_APPROVED: 9,
  ORDER_REJECTED: 10,
  ORDER_SUCCESS: 11,
  properties: {
    1: { name: 'submission created', value: 1, icon: 'edit', color: 'yellow-6' },
    2: { name: 'submission updated', value: 2, icon: 'solution', color: 'blue' },
    3: { name: 'document approved', value: 3, icon: 'solution', color: 'green' },
    4: { name: 'document rejected', value: 4, icon: 'exception', color: 'red' },
    5: { name: 'finance approved', value: 5, icon: 'wallet', color: 'green' },
    6: { name: 'finance rejected', value: 6, icon: 'wallet', color: 'red' },
    7: { name: 'order started', value: 7, icon: 'flag', color: 'blue' },
    8: { name: 'order finished', value: 8, icon: 'flag', color: 'yellow' },
    9: { name: 'order approved', value: 9, icon: 'flag', color: 'green' },
    10: { name: 'order rejected', value: 10, icon: 'flag', color: 'red' },
    11: { name: 'order success', value: 11, icon: 'flag', color: 'yellow' },
  },
};
